using UnityEngine;

public class MovingObstacle : MonoBehaviour
{
    public float moveSpeed = 2f; // Скорость движения препятствия
    public float moveRange = 2f; // Насколько далеко препятствие движется от своей начальной позиции по X

    private Vector3 startPosition;

    void Start()
    {
        startPosition = transform.position;
    }

    void Update()
    {
        // Движение по синусоиде для плавного перемещения влево-вправо
        float newX = startPosition.x + Mathf.Sin(Time.time * moveSpeed) * moveRange;
        transform.position = new Vector3(newX, transform.position.y, transform.position.z);
    }
}
